### ISSUE TITLE
1.1 Evaluating Expressions - problem

### ISSUE THREAD

**Issue by miguel-negrao** [leanprover/functional_programming_in_lean#1]
I've setup lean for use with vscode following the instructions in the vscode extension. I've use elan to make the default lean lean4:nightly-2023-03-11.

When entering the expression

    #eval String.append("Hello, ", "Lean!")

I get the error

```
expression
  String.append
has type
  String → String → String
but instance
  Lean.Eval (String → String → String)
failed to be synthesized, this instance instructs Lean on how to display the resulting value, recall that any type implementing the `Repr` class also implements the `Lean.Eval` class
```

**Comment by miguel-negrao** [comment]
Sorry, read to quickly... no problem with text.

**Comment by david-christiansen** [comment]
No worries :-)
